### ISSUE TITLE
[Bug]: Cannot use a custom TrackingManager

### ISSUE THREAD

**Issue by mlumia** [pimcore/ecommerce-framework-bundle#178]
### Expected behavior

Setting a custom Tracking Manager in the config `tracking_manager_id` should output the tracked codes for the active GoogleTagManager tracker.

The event subscriber [TrackingCodeFlashMessageListener](https://github.com/pimcore/ecommerce-framework-bundle/blob/1.x/src/EventListener/Frontend/TrackingCodeFlashMessageListener.php) should move the flash message tracked codes to the Tracker tracked codes.

The event subscriber [TrackingCodeSubscriber](https://github.com/pimcore/ecommerce-framework-bundle/blob/1.x/src/EventListener/Frontend/TrackingCodeSubscriber.php) should prepend the tracked codes to the `GoogleTagManagerEvents` event block.

---

Info: The use of the Factory is required to get the TrackingManager. Using DI is incorrect. The [documentation example](https://pimcore.com/docs/platform/Ecommerce_Framework/Tracking_Manager/#working-with-tracking-manager) also show the use of DI as the "method" to implement, which is incorrect. 

### Actual behavior

Both EventSubscribers (TrackingCodeSubscriber and TrackingCodeFlashMessageListener) use DI to get the TrackingManager which is not loaded with the $trackers from the [compiler pass](https://github.com/pimcore/ecommerce-framework-bundle/blob/1.x/src/DependencyInjection/Compiler/RegisterConfiguredServicesPass.php#L48-L58).

- [TrackingCodeSubscriber](https://github.com/pimcore/ecommerce-framework-bundle/blob/1.x/src/EventListener/Frontend/TrackingCodeSubscriber.php)
- [TrackingCodeFlashMessageListener](https://github.com/pimcore/ecommerce-framework-bundle/blob/1.x/src/EventListener/Frontend/TrackingCodeFlashMessageListener.php)

The tracked codes by the tracking_manager_id TrackingManager is not output.

### Steps to reproduce

1. Create a custom TrackingManager class
2. Set the `tracking_manager_id` as the custom TrackingManager class
```
pimcore_ecommerce_framework:
    tracking_manager:
        tracking_manager_id: App\Tracking\MyCustomerTrackingManager
        trackers:
            tag_manager:
                id: Pimcore\Bundle\EcommerceFrameworkBundle\Tracking\Tracker\GoogleTagManager
                enabled: true
```
3. Track a product view in a controller:
`$this->factory->getTrackingManager()->trackProductView($product);`
4. Optional to test forwardTrackedCodesAsFlashMessage():
`$this->factory->getTrackingManager()->forwardTrackedCodesAsFlashMessage();`
5. Check HTML output for: `dataLayer.push` which is not output.
