### ISSUE TITLE
[Bug]: The 'kernel' service is synthetic, it needs to be set at boot time when running update index command on 11.3.1

### ISSUE THREAD

**Issue by lucas-langa** [pimcore/ecommerce-framework-bundle#202]
### Pimcore version

11.3.1

### Steps to reproduce

php bin/console ecommerce:indexservice:bootstrap --update-index

### Actual Behavior

429 from opensearch
![image](https://github.com/user-attachments/assets/f24e1596-2c49-48ab-9e46-502d1c94c585)
then "The 'kernel' service is synthetic, it needs to be set at boot time" error
![Screenshot from 2024-09-18 10-30-00](https://github.com/user-attachments/assets/22074b13-9233-48a5-b62b-997d625d2479)

### Expected Behavior

products get saved in opensearch index

**Comment by medovanx** [comment]
I have the same issue on Pimcore 11.4.0 using ES8
![image](https://github.com/user-attachments/assets/8bbc5a12-896c-47d0-b469-fa5591303990)

**Comment by fashxp** [comment]
related to https://github.com/pimcore/data-importer/issues/420?

**Comment by mattamon** [comment]
@lucas-langa Thank you for sharing this bug with us. 

My first note would be, how does this even work with OpenSearch? Currently we are not supporting OpenSearch with the E-Commerce Framework. I would need some more details here if you are able to share them.

@medovanx I trued to reproduce the issue with ES8 in our docker setup, but was not able to reproduce it. 
Can you please also provide more infos about how you setup elasticsearch?

**Comment by medovanx** [comment]
@mattamon

I used docker-compose with the following service
```
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
        ports:
            - "9200:9200"
        volumes:
            - es_data:/usr/share/elasticsearch/data
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
            - xpack.security.enabled=false
```

and contents of `./config/ecommerce/elastic-search.yaml`

```
pimcore_ecommerce_framework:
    index_service:
        tenants:
            EcommerceProductIndex:
                worker_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Worker\ElasticSearch\DefaultElasticSearch8
                config_id: Pimcore\Bundle\EcommerceFrameworkBundle\IndexService\Config\ElasticSearch
                
                config_options:
                    client_config:
                        logging: false
                        indexName: 'product-index'

                    # elasticsearch client name, for Elasticsearch 8 only
                    es_client_name: default

                    index_settings:
                        number_of_shards: 5
                        number_of_replicas: 0
                        max_ngram_diff: 30
                        analysis:
                            analyzer:
                                my_ngram_analyzer:
                                    tokenizer: my_ngram_tokenizer
                                allow_list_analyzer:
                                    tokenizer: standard
                                    filter:
                                      - allow_list_filter
                            tokenizer:
                                my_ngram_tokenizer:
                                    type: ngram
                                    min_gram: 2
                                    max_gram: 15
                                    token_chars: [letter, digit]
                            filter:
                                allow_list_filter:
                                    type: keep
                                    keep_words:
                                      - was
                                      - WAS

pimcore_elasticsearch_client:
    es_clients:
        default:
            hosts: ['%env(ELASTICSEARCH_HOST)%:%env(ELASTICSEARCH_PORT)%']
            logger_channel: 'pimcore.elasticsearch'    
```

The Product class is called "Products" so I specify by running 

```
bin/console \
ecommerce:indexservice:bootstrap --update-index \
--object-list-class Pimcore\\Model\\DataObject\\Products\\Listing```
```

I have the following in services.yaml because it was complaining of this method not being public when running the update-index command

```
    Symfony\Component\Lock\LockFactory:
        public: true
```

The Products class 

Implements **Interface**: `\Pimcore\Bundle\EcommerceFrameworkBundle\Model\IndexableInterface`
Uses this **Trait**: `\App\Ecommerce\IndexService\IndexableTrait`
